name: am_calendar
description: A calendar for the ENSAM students
version: 0.3.1+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  syncfusion_flutter_calendar: 19.2.62
  syncfusion_localizations:  ^19.2.62
  syncfusion_flutter_core:  ^19.2.62
  shared_preferences: ^2.0.5
  http: ^0.13.3
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  flutter_inappwebview: ^5.3.2
  collection: ^1.15.0
  package_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'resources/icons/am-logo.png'

flutter:
  uses-material-design: true
  assets:
    - resources/icons/am-logo.png

