name: am_calendar
description: A calendar for the ENSAM students
version: 2.0.1+28

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  syncfusion_flutter_core: 20.4.44
  syncfusion_flutter_datepicker: 20.4.44
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  http: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_inappwebview: 6.0.0-beta.22
  collection: ^1.17.2
  package_info: ^2.0.2
  mailto: ^2.0.0
  url_launcher: ^6.2.1
  event_bus: ^2.0.0
  provider: ^6.1.1
  icalendar_parser: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: 'resources/icons/am-logo.png'
  image_path_ios: 'resources/icons/am-logo-ios.png'

flutter:
  uses-material-design: true
  assets:
    - resources/icons/am-logo.png
    - packages/timezone/data/latest_10y.tzf
#    - packages/timezone/data/2020a.tzf
  fonts:
    - family: Cloister
      fonts:
        - asset: resources/fonts/CloisterBlack.ttf

